package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallRecord;
import org.linlinjava.litemall.db.domain.LitemallRecordExample;

public interface LitemallRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_record
     *
     * @mbg.generated
     */
    long countByExample(LitemallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_record
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_record
     *
     * @mbg.generated
     */
    int insert(LitemallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_record
     *
     * @mbg.generated
     */
    int insertSelective(LitemallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_record
     *
     * @mbg.generated
     */
    LitemallRecord selectOneByExample(LitemallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_record
     *
     * @mbg.generated
     */
    LitemallRecord selectOneByExampleSelective(@Param("example") LitemallRecordExample example, @Param("selective") LitemallRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_record
     *
     * @mbg.generated
     */
    List<LitemallRecord> selectByExampleSelective(@Param("example") LitemallRecordExample example, @Param("selective") LitemallRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_record
     *
     * @mbg.generated
     */
    List<LitemallRecord> selectByExample(LitemallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_record
     *
     * @mbg.generated
     */
    LitemallRecord selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_record
     *
     * @mbg.generated
     */
    LitemallRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_record
     *
     * @mbg.generated
     */
    LitemallRecord selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallRecord record, @Param("example") LitemallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallRecord record, @Param("example") LitemallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_record
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_record
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}