package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallDocument;
import org.linlinjava.litemall.db.domain.LitemallDocumentExample;

public interface LitemallDocumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    long countByExample(LitemallDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    int insert(LitemallDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    int insertSelective(LitemallDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    LitemallDocument selectOneByExample(LitemallDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    LitemallDocument selectOneByExampleSelective(@Param("example") LitemallDocumentExample example, @Param("selective") LitemallDocument.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    LitemallDocument selectOneByExampleWithBLOBs(LitemallDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    List<LitemallDocument> selectByExampleSelective(@Param("example") LitemallDocumentExample example, @Param("selective") LitemallDocument.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    List<LitemallDocument> selectByExampleWithBLOBs(LitemallDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    List<LitemallDocument> selectByExample(LitemallDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    LitemallDocument selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallDocument.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    LitemallDocument selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    LitemallDocument selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallDocument record, @Param("example") LitemallDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallDocument record, @Param("example") LitemallDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallDocument record, @Param("example") LitemallDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_document
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}