package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallElectronicSignature;
import org.linlinjava.litemall.db.domain.LitemallElectronicSignatureExample;

public interface LitemallElectronicSignatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_electronic_signature
     *
     * @mbg.generated
     */
    long countByExample(LitemallElectronicSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_electronic_signature
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallElectronicSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_electronic_signature
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_electronic_signature
     *
     * @mbg.generated
     */
    int insert(LitemallElectronicSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_electronic_signature
     *
     * @mbg.generated
     */
    int insertSelective(LitemallElectronicSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_electronic_signature
     *
     * @mbg.generated
     */
    LitemallElectronicSignature selectOneByExample(LitemallElectronicSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_electronic_signature
     *
     * @mbg.generated
     */
    LitemallElectronicSignature selectOneByExampleSelective(@Param("example") LitemallElectronicSignatureExample example, @Param("selective") LitemallElectronicSignature.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_electronic_signature
     *
     * @mbg.generated
     */
    List<LitemallElectronicSignature> selectByExampleSelective(@Param("example") LitemallElectronicSignatureExample example, @Param("selective") LitemallElectronicSignature.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_electronic_signature
     *
     * @mbg.generated
     */
    List<LitemallElectronicSignature> selectByExample(LitemallElectronicSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_electronic_signature
     *
     * @mbg.generated
     */
    LitemallElectronicSignature selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallElectronicSignature.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_electronic_signature
     *
     * @mbg.generated
     */
    LitemallElectronicSignature selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_electronic_signature
     *
     * @mbg.generated
     */
    LitemallElectronicSignature selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_electronic_signature
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallElectronicSignature record, @Param("example") LitemallElectronicSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_electronic_signature
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallElectronicSignature record, @Param("example") LitemallElectronicSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_electronic_signature
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallElectronicSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_electronic_signature
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallElectronicSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_electronic_signature
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallElectronicSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_electronic_signature
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}