DROP TABLE IF EXISTS `litemall_applicant`;
CREATE TABLE `litemall_applicant`  (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `user_id` int(11) NULL DEFAULT NULL COMMENT '用户',
  `name` varchar(10) NULL DEFAULT NULL COMMENT '申请人姓名',
  `sex` varchar(10) NULL DEFAULT NULL COMMENT '性别',
  `marital_status` varchar(10) NULL DEFAULT NULL COMMENT '婚姻状态',
  `id_card_number` varchar(20) NULL DEFAULT NULL COMMENT '身份证号',
  `phone_number` varchar(20) NULL DEFAULT NULL COMMENT '联系方式',
  `spouse_name` varchar(20) NULL DEFAULT NULL COMMENT '配偶姓名',
  `applicant_type` varchar(20) NULL DEFAULT NULL COMMENT '申请类别',
  `applicant_amount` varchar(255) NULL DEFAULT NULL COMMENT '申请人金额',
  `recruit_category` varchar(20) NULL DEFAULT NULL COMMENT '新招类别',
  `applicant_category` varchar(20) NULL DEFAULT NULL COMMENT '申请类别',
  `address` varchar(255) NULL DEFAULT NULL COMMENT '申请主体现住址',
  `spouse_id_card_number` varchar(255) NULL DEFAULT NULL COMMENT '配偶身份证号',
  `business_license_url` varchar(255) NULL DEFAULT NULL COMMENT '营业执照正面',
  `business_license_url_2` varchar(255) NULL DEFAULT NULL COMMENT '营业执照反面',
  `labor_contract_url` varchar(255) NULL DEFAULT NULL COMMENT '劳动合同',
  `salary_detail_url` varchar(255) NULL DEFAULT NULL COMMENT '工资明细',
  `id_card_url` varchar(255) NULL DEFAULT NULL COMMENT '身份证正面',
  `id_card_url_2` varchar(255) NULL DEFAULT NULL COMMENT '身份证反面',
  `spouse_id_card_url` varchar(255) NULL DEFAULT NULL COMMENT '配偶身份证正面',
  `spouse_id_card_url_2` varchar(255) NULL DEFAULT NULL COMMENT '配偶身份证反面',
  `marriage_certificate_url` varchar(255) NULL DEFAULT NULL COMMENT '婚姻证首页',
  `marriage_certificate_url_2` varchar(255) NULL DEFAULT NULL COMMENT '婚姻证本人页',
  `residence_booklet_url` varchar(255) NULL DEFAULT NULL COMMENT '户口本首页',
  `residence_booklet_url_2` varchar(255) NULL DEFAULT NULL COMMENT '户口本本人页',
  `credit_report_url` varchar(255) NULL DEFAULT NULL COMMENT '法定代表人信用报告',
  `credit_report_url_2` varchar(255) NULL DEFAULT NULL,
  `spouse_credit_report_url` varchar(255) NULL DEFAULT NULL COMMENT '配偶代表人信用报告',
  `spouse_credit_report_url_2` varchar(255) NULL DEFAULT NULL,
  `undertaking_url` varchar(255) NULL DEFAULT NULL COMMENT '承诺书',
  `lease_contract_url` varchar(255) NULL DEFAULT NULL COMMENT '租赁合同',
  `property_certificate_url` varchar(255) NULL DEFAULT NULL COMMENT '产权证',
  `house_proprietary_certificate_url` varchar(255) NULL DEFAULT NULL COMMENT '房产证',
  `vehicles_certificate_url` varchar(255) NULL DEFAULT NULL COMMENT '车辆权证',
  `bank_reconciliation_url` varchar(255) NULL DEFAULT NULL COMMENT '银行对账',
  `surety_id_card_url` varchar(255) NULL DEFAULT NULL COMMENT '担保人身份证正面',
  `surety_id_card_url_2` varchar(255) NULL DEFAULT NULL COMMENT '担保人身份证反面',
  `extra_url` varchar(255) NULL DEFAULT NULL COMMENT '其他照片',
  `add_time` datetime(0) NULL DEFAULT NULL COMMENT '新增时间',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) NULL DEFAULT 0 COMMENT '逻辑删除',
  `submit_status` int(10) NULL DEFAULT 0 COMMENT '提交状态',
  `bank_id` varchar(1023) NULL DEFAULT NULL COMMENT '受理银行采用JSON数组格式',
  `hs_business_license_type` varchar(255) NULL DEFAULT NULL COMMENT '营业执照类型',
  `hs_applicant` varchar(255) NULL DEFAULT NULL COMMENT '法定代表人/申请人',
  `hs_unified_social_credit_code` varchar(255) NULL DEFAULT NULL COMMENT '统一社会信用代码',
  `hs_applicant_adress` varchar(255) NULL DEFAULT NULL COMMENT '身份证地址',
  `hs_rigster_date` datetime(0) NULL DEFAULT NULL COMMENT '注册日期',
  `hs_employment_business_license_no` varchar(255) NULL DEFAULT NULL COMMENT '就业创业证编号（申请主体）',
  `hs_employees_info` varchar(255) NULL DEFAULT NULL COMMENT '带动就业人员信息',
  `hs_active_employees` int(11) NULL DEFAULT NULL COMMENT '在职人数',
  `hs_recruit_people` int(11) NULL DEFAULT NULL COMMENT '当年新招人数',
  `hs_mark` varchar(255) NULL DEFAULT NULL COMMENT '其他备注',
  `hs_recuit_rate` varchar(255) NULL DEFAULT NULL COMMENT '新招用员工占比',
  `hs_comment` varchar(255) NULL DEFAULT NULL COMMENT '市人社部门\r\n意见\r\n市人社部门\r\n意见\r\n',
  `hs_audit_date` datetime(0) NULL DEFAULT NULL COMMENT '人社审核日期',
  `hs_operator` varchar(255) NULL DEFAULT NULL COMMENT '人社经办人',
  `hs_top_amount` decimal(20, 0) NULL DEFAULT NULL COMMENT '最高批复额度',
  `sc_business_address` varchar(255) NULL DEFAULT NULL COMMENT '营业地址',
  `sc_property_right` varchar(255) NULL DEFAULT NULL COMMENT '产权性质',
  `sc_applicant_credit_report` varchar(255) NULL DEFAULT NULL COMMENT '申请人信用报告',
  `sc_spouse_credit_report` varchar(255) NULL DEFAULT NULL COMMENT '配偶信用报告',
  `sc_guarantor` varchar(255) NULL DEFAULT NULL COMMENT '担保人姓名',
  `sc_guarantor_asset` varchar(255) NULL DEFAULT NULL COMMENT '担保人抵押资产情况',
  `sc_extra_info` varchar(255) NULL DEFAULT NULL COMMENT '其他补充情况',
  `sc_comment` varchar(255) NULL DEFAULT NULL COMMENT '担保公司意见',
  `sc_letter_intent_url` varchar(255) NULL DEFAULT NULL COMMENT '担保意向书内容',
  `sc_audit_date` datetime(0) NULL DEFAULT NULL COMMENT '担保公司审核日期',
  `sc_operator` varchar(255) NULL DEFAULT NULL COMMENT '担保公司经办人',
  `b_bank_id` int(20) NULL DEFAULT NULL COMMENT '受理银行ID',
  `b_name` varchar(255) NULL DEFAULT NULL COMMENT '受理银行',
  `b_sub_branch` varchar(255) NULL DEFAULT NULL COMMENT '支行',
  `b_opertator` varchar(255) NULL DEFAULT NULL COMMENT '经办人',
  `b_credit` varchar(255) NULL DEFAULT NULL COMMENT '授信额度',
  `b_lending_date` datetime(0) NULL DEFAULT NULL COMMENT '放贷日期',
  `b_period_loan` varchar(255) NULL DEFAULT NULL COMMENT '贷款期限',
  `b_repayment` varchar(255) NULL DEFAULT NULL COMMENT '还款方式',
  `b_interest_rate` varchar(255) NULL DEFAULT NULL COMMENT '利率',
  `b_interest_period` varchar(255) NULL DEFAULT NULL COMMENT '利息/期',
  `b_comment` varchar(255) NULL DEFAULT NULL COMMENT '银行受理情况',
  `b_audit_date` datetime(0) NULL DEFAULT NULL COMMENT '银行审核日期',
  `b_auditor` varchar(255) NULL DEFAULT NULL COMMENT '银行审核人',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COMMENT='申请人' ;


DROP TABLE IF EXISTS `litemall_applicant_bank`;
CREATE TABLE `litemall_applicant_bank`  (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `applicant_id` int(11) NULL DEFAULT NULL COMMENT '申请人ID',
  `bank_id` int(11) NULL DEFAULT NULL COMMENT '受理人ID',
  `credit` varchar(20) NULL DEFAULT NULL COMMENT '额度',
  `lending_date` datetime(0) NULL DEFAULT NULL COMMENT '放款日期',
  `period_loan` varchar(11) NULL DEFAULT NULL COMMENT '货款期限',
  `repayment` varchar(255) NULL DEFAULT NULL COMMENT '还款方式',
  `interest` varchar(10) NULL DEFAULT NULL COMMENT '利息',
  `interest_period` varchar(255) NULL DEFAULT NULL COMMENT '利息周',
  `audit_comment` varchar(255) NULL DEFAULT NULL COMMENT '受力情况',
  `status` int(5) NULL DEFAULT NULL COMMENT '审批状态',
  `opertator` varchar(255) NULL DEFAULT NULL COMMENT '经办人',
  `add_time` datetime(0) NULL DEFAULT NULL,
  `update_time` datetime(0) NULL DEFAULT NULL,
  `deleted` tinyint(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COMMENT='申请人—银行' ;

DROP TABLE IF EXISTS `litemall_bank`;
CREATE TABLE `litemall_bank`  (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `icon` varchar(1023)  DEFAULT NULL COMMENT '小图标',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '银行',
  `contact` varchar(255) NULL DEFAULT NULL COMMENT '联系方式',
  `address` varchar(255) NULL DEFAULT NULL COMMENT '地址',
  `sub_branch` varchar(255) NULL DEFAULT NULL COMMENT '支行',
  `loan` int(10) NULL DEFAULT NULL COMMENT '货款额度',
  `interest` varchar(10)  DEFAULT NULL COMMENT '利息',
  `add_time` datetime(0) NULL DEFAULT NULL COMMENT '新增时间',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  `role_id` int(11) NULL DEFAULT NULL,
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '删除',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COMMENT= '申请人—银行' ;

DROP TABLE IF EXISTS `litemall_document`;
CREATE TABLE `litemall_document`  (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `doc_type` varchar(20) NULL DEFAULT NULL COMMENT '文档类型',
  `doc_name` varchar(20) NULL DEFAULT NULL COMMENT '文档名称',
  `detail` text NULL COMMENT '文档详细介绍，是富文本格式',
  `add_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) NULL DEFAULT 0 COMMENT '逻辑删除',
  `creator` varchar(20) NULL DEFAULT NULL COMMENT '创建人',
  `updator` varchar(20) NULL DEFAULT NULL COMMENT '修改人',
  `active` tinyint(1) NULL DEFAULT 0 COMMENT '启用状态',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COMMENT= "富文本"



